# SPDX-License-Identifier: BSD-3-Clause-Clear

obj-$(CONFIG_STANDALONE_MT7921_COMMON) += standalone-mt7921-common.o
obj-$(CONFIG_STANDALONE_MT7921U) += standalone-mt7921u.o

standalone-mt7921-common-y := mac.o mcu.o regd.o main.o init.o debugfs.o
standalone-mt7921u-y := usb.o
